title: Site Title
description: Site description
variable: site variable

collections:
  c1:
    output: true
    permalink: /:collection/:path
  c2:
    output: true

plugins:
  - jekyll-avatar
  - jekyll-gist
  - jekyll-github-metadata

gist:
  noscript: false

config_data:
  k1: first
  k2: second
  k0: third
  k5: fourth
  k4: fifth
  k3: sixth
